DROP DATABASE IF EXISTS streetvnyl;
CREATE DATABASE streetvnyl;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL
);

CREATE TABLE playlists (
  id SERIAL PRIMARY KEY,
  uid INTEGER REFERENCES users (id),
  title VARCHAR NOT NULL,
  lat FLOAT NOT NULL,
  lng FLOAT NOT NULL
);

CREATE TABLE tracks (
  id SERIAL PRIMARY KEY,
  playlist_id INTEGER REFERENCES playlists (id),
  title VARCHAR NOT NULL,
  artist VARCHAR NOT NULL,
  preview_url VARCHAR NOT NULL
);
